main:
  window_width: 1280
  window_height: 720

generic:
  window_width: 640
  window_height: 400

background:
  image: data/images/MOSS.jpeg

track:
  min_confidence: 0.0
  nms_max_overlap: 1.0
  min_detection_height: 0.0
  max_cosine_detection: 0.7
  nn_budget: 1